name: ai4beg
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - ipykernel
  - ipython
  - ipywidgets
  - jupyter
  - matplotlib=3.9
  - numpy=1.26
  - python
  - requests=2.32
  - scikit-learn
  - scipy=1.13
  - pip
  - conda-forge::opencv
  - setuptools
  - pytorch
  - torchtext
  - torchvision
  - torchdata
  - pip:
    - -r requirements.txt
